### ISSUE TITLE
status.py has issues on client-node upgrades (and restarts?)

### ISSUE THREAD

**Issue by GuybrushX** [matsuro-hadouken/casper-tools#48]
When the client-node gets upgraded you have to restart status.py because the display is totally corrupted.

Not a big issue but a bit annoying and maybe it's an easy fix?

You can reproduce when you install a new node and wait for the now 4 upgrades. Maybe also just stop and start the client-node? I think the endpoints aren't reachable for a few seconds which corrupts the display.

**Comment by matsuro-hadouken** [comment]
Thank you for report @GuybrushX 

When node goes trough upgrade stage many functions are not working as expected, metrics looks absolute mess at this point.
We need to check for appropriate triggers to determinate actual moment of upgrade, in fact metrics come back to expected state slowly, because we always calculate allot of  average values over time, most monitored parameters will have no sense for some minutes or an hour. Will takes a while to implement properly, we will look for solution.

**Comment by RapidMark** [comment]
I've been looking at this during the last few upgrades, and thought I had it fixed before. I'm continuing to fix and wait for the next upgrade to verify,

Oh and stopping and starting is what I used to test it before... maybe I'll setup a new node to test again... thanks for the idea

**Comment by GuybrushX** [comment]
Short update:
During upgrades the complete window got messed up not only statistics. Unfortunately I didn't take a screenshot - will take one next time.

@RapidMark
Actually I'm using your fork and since a few versions and running on the testnet I always get the following message after a few hours of running (the mainnet is on an older version and is running since a few days already):
Traceback (most recent call last):
  File "./status.py", line 2175, in <module>
    main()
  File "./status.py", line 2172, in main
    curses.wrapper(draw_menu)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "./status.py", line 1996, in draw_menu
    casper_peers()
  File "./status.py", line 1337, in casper_peers
    for ip in peer_scan_dict:
RuntimeError: dictionary changed size during iteration

I'm running the latest commit (git show output):
commit d53f26bcbe394d594e2d2fc12c3ae17f74091ef0 (HEAD -> master, origin/master, origin/HEAD)

The mainnet is at the following commit and working since a few days (git show output):
commit 195bab6342c289007f3d975b95a7f2766a2ac3c8 (HEAD -> master, origin/master, origin/HEAD)

So something changed and broke something.

I'm not sure if this is related so let me know if I should create a new issue for this.

**Comment by RapidMark** [comment]
Thanks,

I was using the main dictionary and it got updated during a refresh, so I made a copy of it and used that when printing the update.

I have checked it in, let me know if that fixes your issue.

Thanks


  *   Mark

**Comment by GuybrushX** [comment]
Thank you for your fast reply. I updated about 2h after your message. Unfortunately it didn't fix the issue.

Here is the message:
Traceback (most recent call last):
  File "./status.py", line 2176, in <module>
    main()
  File "./status.py", line 2173, in main
    curses.wrapper(draw_menu)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "./status.py", line 1997, in draw_menu
    casper_peers()
  File "./status.py", line 1338, in casper_peers
    for ip in local_peer_scan_dict:
RuntimeError: dictionary changed size during iteration

Let me know if I can do something to support you.

**Comment by RapidMark** [comment]
OK, try it again… and thanks for helping 😊


  *   Mark

**Comment by GuybrushX** [comment]
Thank *you* for your fast updates :-)

It also crashed today on the mainnet node which was running an older commit so it's not a new issue:
Traceback (most recent call last):
  File "./status.py", line 2157, in <module>
    main()
  File "./status.py", line 2154, in main
    curses.wrapper(draw_menu)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "./status.py", line 1978, in draw_menu
    casper_peers()
  File "./status.py", line 1324, in casper_peers
    for ip in peer_scan_dict:
RuntimeError: dictionary changed size during iteration

$ git show
commit 195bab6342c289007f3d975b95a7f2766a2ac3c8 (HEAD -> master, origin/master, origin/HEAD)

I've pulled the latest version and let's see if it's fixed now. Running it on both nodes now with the latest version. I think it's crashing more frequently on the testnet because there is more activity - at least in the Casper Deploys section.

**Comment by GuybrushX** [comment]
Update:
Both instances (mainnet + testnet) are still up and running -> so far it looks like your last commit fixed it :-)

**Comment by GuybrushX** [comment]
Both instances are still running without any interruption and since the new staking UI was released there is more traffic, too. So I would say the crashes are fixed.

**Comment by matsuro-hadouken** [comment]
sorted
