### ISSUE TITLE
Feature request: add timestamps

### ISSUE THREAD

**Issue by GuybrushX** [matsuro-hadouken/casper-tools#53]
Hello again,

would be nice to have timestamps for a few things:
- for screenshots to see how current it is -> maybe put it on the right site of the "Casper Node Launcher", there seems to be enough space and that block is also provided usually (I skip Casper Deploys usually, just too much and not needed information for a status update)
- Maybe also add timestamps or refresh intervals to some areas like "Casper Transfers", "Casper Events", "Casper Deploys" and wherever it makes sense. In case this is real time data from the network it's a different story, of course

**Comment by RapidMark** [comment]
Need more info... you mean (and please add/elaborate)
    what time is it now (Casper Node Launcher)? 
    what time did this block start (Casper Block Info)?

**Comment by GuybrushX** [comment]
> Need more info... you mean (and please add/elaborate)
> what time is it now (Casper Node Launcher)? -> current date/time to show on screenshots from when it was taken
> what time did this block start (Casper Block Info)? -> not sure if this is useful

Currently I don't see when information got updated or when deploys happened.

But yeah, most important and probably easy addition would be the timestamp for screenshots.

Hope it's clear now?

**Comment by RapidMark** [comment]
Added a few.... still contemplating how to add them to deploys (since there really isn't a lot of space, but I'll find a way

**Comment by GuybrushX** [comment]
The new "Time: " Looks great, better than I thought! ;-)

I thought to put it on the right side in the frame next to the title (same hight) or in the right corner. If you have the information already I would add some more but also in the right side in the frame - similar to how you did it with the "Casper Peers - Next scan in ..." frame:
Casper Validator Info **- Last Update: <Timestamp>** OR Casper Validator Info **- Next update/scan in <hh:mm:ss>**
Casper Deploys **- Last Deploy: <Timestamp>**
Casper Transfers **- Last Transfer: <Timestamp>**

Or maybe put it in the bottom of the frame if it's not enough space.

Since English isn't my native language the wording should be changed accordingly.

It's all not so critical but some useful addition I think.

**Comment by matsuro-hadouken** [comment]
Should be cool by now.
