### ISSUE TITLE
Some areas don't get updated anymore after some time

### ISSUE THREAD

**Issue by GuybrushX** [matsuro-hadouken/casper-tools#58]
I'm running status.py on 3 nodes:

- 2x mainnet
- 1x testnet

A few strange things are happening:
The "Casper Transfers" area on the mainnet node 1 is stuck at Block "99976" and it should be "130395" like the other mainnet node 2:
![image](https://user-images.githubusercontent.com/17174280/125141933-18213f80-e11f-11eb-8de4-bcea06ab3aa1.png)

On the mainnet node 2 it doesn't update the price anymore and it still shows $0.1822 which is a bit outdated:
![image](https://user-images.githubusercontent.com/17174280/125141972-2d966980-e11f-11eb-894c-80ad00236543.png)

The testnet node suddenly shows old "Casper Transfers":
![image](https://user-images.githubusercontent.com/17174280/125142056-70584180-e11f-11eb-9fdb-7c471131a09c.png)

Is this an known issue? Anything I can do about that to force a refresh or just restart it from time to time (which will kill the Avg. Reward calculation and all other stats, of course so I want to avoid that).

**Comment by RapidMark** [comment]
Are these still happening?

**Comment by matsuro-hadouken** [comment]
> Are these still happening?

Lets assume is not for now
