### ISSUE TITLE
Misleading or wrong message after staging an upgrade?

### ISSUE THREAD

**Issue by GuybrushX** [matsuro-hadouken/casper-tools#60]
I just staged the recent testnet upgrade to 1.2.1 and the following message appeared:
![image](https://user-images.githubusercontent.com/17174280/125143007-e9589880-e121-11eb-95fd-984cb1e71f62.png)

Under "Casper Block Info" it looks fine.

Under "Casper Peers -> It appears someone has an upgrade staged for 1143 and we do not!" it seems that something is wrong. For me it reads like I have to stage an upgrade which I did already?

I remember I saw the same message when I set up a node recently so I think this is a wrong message.

**Comment by RapidMark** [comment]
I think I fixed this already, please confirm

**Comment by matsuro-hadouken** [comment]
We believe it fixed, but need double check on the next network upgrade just to be completely sure, will leave open for now.

**Comment by matsuro-hadouken** [comment]
Recently testnet upgrade show no sign of issue, considered fixed.
