### ISSUE TITLE
"Config File" and "Storage Path" values in status.py become incorrect after 1_4_5

### ISSUE THREAD

**Issue by mathematicw** [matsuro-hadouken/casper-tools#79]
The issue is relevant to 1_4_5 version.
The string **Config File :** should be /etc/casper/1_4_5/config.toml , but it has a value: "ps"
The string **Storage Path :** should reflect the path that is written in config.toml, even if it differs from the default one, but since last update it is reflecting the default path : _/var/lib/casper/casper-node_
![Screenshot_2022-03-21_12-53-16](https://user-images.githubusercontent.com/77671963/159238463-05adcc7e-e994-41f4-8b94-7103b364370e.png)

And so in **Disk Usage** section it reflects **Free Space** not on the factual DB path, but on the default instead.

**Comment by mathematicw** [comment]
after restarting the node, the application continues to work correctly

**Comment by matsuro-hadouken** [comment]
Appears to be no issue
